// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Codemirror: typeof import('./src/components/Codemirror/index.vue')['default']
    DevTools: typeof import('./src/components/DevTools/index.vue')['default']
    Dome: typeof import('./src/components/DevTools/dome.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    Explorer: typeof import('./src/components/Explorer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    MainWorkspace: typeof import('./src/components/MainWorkspace/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
    Test1: typeof import('./src/components/test1.vue')['default']
    VSCode: typeof import('./src/components/VSCode/index.vue')['default']
    Workspace: typeof import('./src/components/Workspace/index.vue')['default']
  }
}

export {}
